// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2jri657dG89HoDfNdMM_Vczu4NKSjkDY',
    appId: '1:966645829652:web:9af4ef8216bac55bc25701',
    messagingSenderId: '966645829652',
    projectId: 'flutter-shopping-app-1b743',
    authDomain: 'flutter-shopping-app-1b743.firebaseapp.com',
    storageBucket: 'flutter-shopping-app-1b743.firebasestorage.app',
    measurementId: 'G-STLDG1ZCR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhXCR38XtGXxfZX8a329ZetCWCZSGG8G4',
    appId: '1:966645829652:android:e170fda55d4ba4b7c25701',
    messagingSenderId: '966645829652',
    projectId: 'flutter-shopping-app-1b743',
    storageBucket: 'flutter-shopping-app-1b743.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbSArGqkhgWLA8s-73psT9_YhDCW7I208',
    appId: '1:966645829652:ios:d16cfa9366d3eac9c25701',
    messagingSenderId: '966645829652',
    projectId: 'flutter-shopping-app-1b743',
    storageBucket: 'flutter-shopping-app-1b743.firebasestorage.app',
    iosBundleId: 'com.example.firstFlutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbSArGqkhgWLA8s-73psT9_YhDCW7I208',
    appId: '1:966645829652:ios:d16cfa9366d3eac9c25701',
    messagingSenderId: '966645829652',
    projectId: 'flutter-shopping-app-1b743',
    storageBucket: 'flutter-shopping-app-1b743.firebasestorage.app',
    iosBundleId: 'com.example.firstFlutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2jri657dG89HoDfNdMM_Vczu4NKSjkDY',
    appId: '1:966645829652:web:ebe56165d144145cc25701',
    messagingSenderId: '966645829652',
    projectId: 'flutter-shopping-app-1b743',
    authDomain: 'flutter-shopping-app-1b743.firebaseapp.com',
    storageBucket: 'flutter-shopping-app-1b743.firebasestorage.app',
    measurementId: 'G-QH42PLN05Y',
  );
}
